### ISSUE TITLE
For -02 version

### ISSUE THREAD

**Issue by jlivingood** [wkumari/draft-livingood-dnsop-negative-trust-anchors#12]
1 - Update Appendix B to show -01 and -02 changes
http://tools.ietf.org/html/draft-livingood-dnsop-negative-trust-anchors-01#appendix-B

2 - Remove resolved items from Appendix C and/or make each one a new issue in GitHub and add a pointer to the git issue tracker
http://tools.ietf.org/html/draft-livingood-dnsop-negative-trust-anchors-01#appendix-C

**Comment by wkumari** [comment]
1: Done / no longer relevant. 

2: Done.
